name: rl
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=21.1.3
  - numpy=1.19.2
  - absl-py=0.13.0
  - pyparsing=2.4.7
  - jupyterlab=3.0.14
  - scikit-image=0.18.1
#  - nvidia::cudatoolkit=11.1
#  - nvidia::cudatoolkit=10.2
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
#  - pytorch::cudatoolkit==10.2
  - pip:
      - termcolor==1.1.0
      - git+https://github.com/deepmind/dm_control.git
      - tb-nightly
      - imageio==2.9.0  # need to comment out two lines for m1 macs
      - imageio-ffmpeg==0.4.4
      - hydra-core==1.1.0
      - hydra-submitit-launcher==1.1.6
      - pandas==1.3.0
      - ipdb==0.13.9
      - yapf==0.31.0
#      - mujoco_py==2.0.2.13  #older version?
      - sklearn==0.0
      - matplotlib==3.4.2
      - opencv-python==4.5.3.56
      - PyOpenGL-accelerate
      - ale-py==0.7.2
      - gym==0.21.0

#Atari
#  pip install autorom[accept-rom-license]
#-OR-
#  pip install autorom
#  AutoROM --accept-license
#THEN:
#  mkdir Atari_ROMS
#  AutoROM --install-dir ./Atari_ROMS
#  ale-import-roms ./ATARI_ROMS

#MuJoCo
#  mkdir ~/.mujoco
#  Download mujoco from here: https://mujoco.org/download
#  Unrar, unzip, and move folder into ~/.mujoco
#  pip install git+https://github.com/deepmind/dm_control.git