defaults:
  - _self_
  - task@_global_: dmc/quadruped_walk
#  - task@_global_: brax/brax_halfcheetah-v0
#  - task@_global_: atari/pong
  - override hydra/launcher: submitit_local


# environments/domain
envs: dmc
# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 4000
#num_seed_frames: 10
max_episode_frames: false
truncate_episode_frames: false
#max_episode_len: 27000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
#num_eval_episodes: 1
# snapshot
save_snapshot: false
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
#replay_buffer_num_workers: 1
#store_every_frames: false
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: true
# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 50

agent:
  _target_: agents.DrQV2Agent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  discrete: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
#    cpus_per_task: 1
    gpus_per_node: 1
#    gpus_per_node: 0
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
